[package]
name = "sc-util"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "scu"
path = "src/main.rs"

[dependencies]
app_dirs2 = "2.4.0"
clap = { version = "3.1.12", features = ["derive"] }
fs_extra = "1.2.0"
normpath = "0.3.2"
serde = { version = "1.0.136 ", features = ["derive"] }
serde_json = "1.0.79"

[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"
